version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
  app:
    image: ghcr.io/kon1ch1wa/performance:latest
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=performance
  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - HOSTNAME=rabbitmq
      - NODENAME=rabbitmq@rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
